  version: '3.10'

  services:
    go-api-basic-build-scratch:
      build: .
      container_name: app
      ports:
        - "0.0.0.0:8080:8080"
      restart: no

    db:
      container_name: db
      image: postgres
      restart: no
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: mydb
      ports:
        - "0.0.0.0:5432:5432"
      # volumes:
      #   - ./init:/docker-entrypoint-initdb.d 


    nginx:
        build: ./certginx 
        container_name: certginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./certs:/etc/letsencrypt
          - ./certbot-www:/var/www/certbot
        environment:
          DOMAIN: ${DOMAIN}
          EMAIL: ${EMAIL}
        depends_on:
          - go-api-basic-build-scratch