name: Deploy to VPS

on:
  push:
    branches: 
    -  dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd sussy_project
            git clone -b dev https://${{ github.repository_owner }}:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
            docker compose build --no-cache
            chmod +x ./gen_env.sh
            ./gen_env.sh
            docker compose up -d
